name: Rust

on:
  push:         {branches: [ master ]}
  pull_request: {branches: [ master ]}

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    name: Windows 2019 Server
    runs-on: windows-2019
    steps:
    - {uses: actions/checkout@v2}
    - {name:  Info MSRV,                      run: rustc -V && cargo -V && cmd /C ver                 }
    - {name: Build MSRV (default features),   run: cargo build --target-dir=target/msrv               }
    - {name:  Test MSRV (default features),   run: cargo test  --target-dir=target/msrv               }
    - {name: Build MSRV (all features),       run: cargo build --target-dir=target/msrv --all-features}
    - {name:  Test MSRV (all features),       run: cargo test  --target-dir=target/msrv --all-features}
  linux:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - {uses: actions/checkout@v2}
    - {name:  Info MSRV,                      run: rustc -V && cargo -V && cat /proc/version /etc/*-release}
    - {name: Build MSRV (default features),   run: cargo         build      --target-dir=target/msrv                  }
    - {name:  Test MSRV (default features),   run: cargo         test       --target-dir=target/msrv                  }
    - {name: Build MSRV,                      run: cargo         build      --target-dir=target/msrv    --all-features}
    - {name:  Test MSRV,                      run: cargo         test       --target-dir=target/msrv    --all-features}
    - {name:  Info Stable,                    run: rustc +stable -V && cargo +stable -V}
    - {name: Build Stable,                    run: cargo +stable build      --target-dir=target/stable  --all-features}
    - {name:  Test Stable,                    run: cargo +stable test       --target-dir=target/stable  --all-features}
    - {name: Install Nightly,                 run: rustup toolchain install nightly -c miri}
    - {name:  Info Nightly,                   run: rustc +nightly -V && cargo +nightly -V}
    - {name:  Miri Nightly Tests,             run: cargo +nightly miri test --target-dir=target/nightly --all-features}
    - {name:  Miri Nightly Example debugger,  run: cargo +nightly miri run  --target-dir=target/nightly --all-features --example debugger}
